name: Compile LaTeX and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      run: sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Compile LaTeX files
      run: |
        mkdir -p output
        for file in *.tex; do
          pdflatex -output-directory=output "$file" || exit 1
        done

    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdfs
        path: output/*.pdf

    - name: Generate HTML for GitHub Pages
      run: |
        echo "<html><body>" > index.html
        echo "<h1>Documentazione PDF</h1>" >> index.html
        for pdf in output/*.pdf; do
          title=$(basename "$pdf" .pdf)
          echo "<h2>${title}</h2><a href='output/${title}.pdf'>Download ${title}</a><br>" >> index.html
        done
        echo "</body></html>" >> index.html

    - name: Upload HTML as artifact
      uses: actions/upload-artifact@v3
      with:
        name: index-html
        path: index.html
